# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private"
class Imager < Formula
  desc "Automated image updates"
  homepage "https://github.com/jamf/imager"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/jamf/imager/releases/download/v0.1.0/imager-darwin-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "19e80af99621affea6e7fff545dcba0f5f48c0bf274c2399e61fa568231ce3c9"

      def install
        bin.install "imager"
      end
    end
    on_arm do
      url "https://github.com/jamf/imager/releases/download/v0.1.0/imager-darwin-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ca380afd57e831b4b9be3d44ea16c053c43176e2a8d01b2cfe675e6bed6f09ce"

      def install
        bin.install "imager"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jamf/imager/releases/download/v0.1.0/imager-linux-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "3b498acbd1c061c6cbaae83bd89d0d7c194e4d67f889daadbfa860b88da930ca"

        def install
          bin.install "imager"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jamf/imager/releases/download/v0.1.0/imager-linux-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "a0a47e2f24a03d8de76eabb96f87f1fa589b52a2120d72852a66d2d648d8e220"

        def install
          bin.install "imager"
        end
      end
    end
  end
end
