# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private"
class Melange < Formula
  desc "A command-line tool of tools."
  homepage "https://github.com/jamf/melange"
  version "1.1.1"

  on_macos do
    on_intel do
      url "https://github.com/jamf/melange/releases/download/v1.1.1/melange_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "88de9c91957c2137e2a2a71202f30047b4448f950958634d36ed91703ec35164"

      def install
        bin.install "melange"
      end
    end
    on_arm do
      url "https://github.com/jamf/melange/releases/download/v1.1.1/melange_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "be633794fa31179af27edbace165f140b7468d4b8772114c4563d440e17d9c9d"

      def install
        bin.install "melange"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jamf/melange/releases/download/v1.1.1/melange_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "f4d312ea372cf3683d246dab0b594251403c0b3158798f7eb539d55a280103f3"

        def install
          bin.install "melange"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jamf/melange/releases/download/v1.1.1/melange_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "07ed912d1878e0268c7bf7c399048ef980a461384eedef07855e60f3a2e8167a"

        def install
          bin.install "melange"
        end
      end
    end
  end

  conflicts_with "chainguard-dev/tap/melange"
  conflicts_with "melange"
end
