# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private"
class Melange < Formula
  desc "A command-line tool of tools."
  homepage "https://github.com/jamf/melange"
  version "1.1.0"

  on_macos do
    on_intel do
      url "https://github.com/jamf/melange/releases/download/v1.1.0/melange_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8398242cea4eee4d05496df7dcad6157bfcb339f83a5a9a58e5f5d98c765575b"

      def install
        bin.install "melange"
      end
    end
    on_arm do
      url "https://github.com/jamf/melange/releases/download/v1.1.0/melange_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d7da96ea140cedec6f1c36753f6fff3dc598fa6972776d3b05710990302fd62e"

      def install
        bin.install "melange"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jamf/melange/releases/download/v1.1.0/melange_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "502a8286ca13677896879ab5344ed2ae760fa8dbc479f4a7838b725a979ee021"

        def install
          bin.install "melange"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jamf/melange/releases/download/v1.1.0/melange_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "004c6234ee658a325bb98f89b5db6955f11b1337f975006522490f1ec13288d6"

        def install
          bin.install "melange"
        end
      end
    end
  end

  conflicts_with "chainguard-dev/tap/melange"
  conflicts_with "melange"
end
