# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Melange < Formula
  desc "A command-line tool of tools."
  homepage ""
  version "1.0.1"

  on_macos do
    on_intel do
      url "https://github.com/jamf/melange/releases/download/v1.0.1/melange_Darwin_x86_64.tar.gz"
      sha256 "ebb8555d1b150ffb2ee7b287f25384bb55922d6ce9f29ceed16454dc7e2ed9b4"

      def install
        bin.install "melange"
      end
    end
    on_arm do
      url "https://github.com/jamf/melange/releases/download/v1.0.1/melange_Darwin_arm64.tar.gz"
      sha256 "d414c5ed748e62df164b90e86e0e4de722bf14338222984f66b33e1f2b476463"

      def install
        bin.install "melange"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jamf/melange/releases/download/v1.0.1/melange_Linux_x86_64.tar.gz"
        sha256 "f89dbfa855affd79ad1f956535631e3671d78cb71a2336c707584c2b0f33d319"

        def install
          bin.install "melange"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jamf/melange/releases/download/v1.0.1/melange_Linux_arm64.tar.gz"
        sha256 "6f22a0a74827e80907aa528dbb81895efc5227a0b370daeb3c3b15e38dab7a16"

        def install
          bin.install "melange"
        end
      end
    end
  end
end
